name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: .Class files Upload
        uses: actions/upload-artifact@v3
        with:
          name: .Class files
          path: build/classes/java/main/
          if-no-files-found: warn

